### ISSUE TITLE
producer init template is missing

### ISSUE THREAD

**Issue by VuokkoVuorinnen** [voxpupuli/puppet-kafka#13]
Error: Could not find template 'kafka/producer.init.erb' at /modules/kafka/manifests/producer/service.pp:23 on node localhost
Error: Could not find template 'kafka/producer.init.erb' at /modules/kafka/manifests/producer/service.pp:23 on node localhost

**Comment by dhoppe** [comment]
Hello Vuokko, 

could you please provide more information? For example the class parameters you used. 

Kind regards,
Dennis

**Comment by VuokkoVuorinnen** [comment]
Unfortunately I don't have access to the project I used the code for...
