### ISSUE TITLE
Java should not be installed by default

### ISSUE THREAD

**Issue by LionelCons** [voxpupuli/puppet-kafka#180]
It is very likely that Java is already installed on the system so the module should not install it by default.

This would be consistent for instance with ZooKeeper, see https://github.com/deric/puppet-zookeeper/blob/master/manifests/params.pp#L80:
```
  $install_java = false
```

**Comment by igalic** [comment]
@LionelCons this sounds very sensible!
would you like to provide a patch for that?

**Comment by LionelCons** [comment]
Yes. Will do later today...
