### ISSUE TITLE
Enable customized log4j.properties files

### ISSUE THREAD

**Issue by elnormeo** [voxpupuli/puppet-kafka#200]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: current
- Ruby: current
- Distribution: current
- Module version: current

## How to reproduce (e.g Puppet code you use)
Let Kafka run for several days.

## What are you seeing
Logfiles are rotated but never deleted. Even logrotate does not work in this case.

## What behaviour did you expect instead
Possibility to configure the logfiles retention in this puppet module

## Output log
n/a

**Comment by ffrank** [comment]
Hi, what do you mean by "even logrotate does not work"?

Have you implemented logrotate to remove log files, but it won't work for some reason? What is the reason?

**Comment by AlexWerz** [comment]
We have the same problem. Our Kafka runs for several days, logs are created and rotated daily but never actually deleted. In rare cases they fill the harddisk until free space runs out.

**Comment by witchbutter** [comment]
The recommended way to do this is detailed here -> https://community.hortonworks.com/content/supportkb/49706/kafka-log-file-rotation-based-on-file-size.html
It would be simple to add with a log4j.properties template.

**Comment by bastelfreak** [comment]
@witchbutter thanks for pointing this out. Could you provide a patch for this?
