### ISSUE TITLE
It should be possible to start a broker with the -daemon option

### ISSUE THREAD

**Issue by LionelCons** [voxpupuli/puppet-kafka#230]
Currently, the `systemd` unit script created by this module will always contain something like:
```
[Service]
Type=simple
ExecStart=/usr/share/kafka-1.0.0/bin/kafka-server-start.sh /etc/kafka/server.properties
```

It should be possible to pass the `-daemon` option to `kafka-server-start.sh`. As a side effect, the broker's `stdout` will be redirected to a file instead of `syslog`. The goal would be to end up with something like:
```
[Service]
Type=forking
ExecStart=/usr/share/kafka-1.0.0/bin/kafka-server-start.sh -daemon /etc/kafka/server.properties
```

Of course, this should be optional and controlled by yet another parameter.

**Comment by juniorsysadmin** [comment]
Perhaps, but even better would be the ability to Bring Your Own `systemd` unit script, with `template('kafka/unit.erb')` being a variable coming from a parameter rather than a fixed value.

**Comment by LionelCons** [comment]
@juniorsysadmin This is a good idea but it might be tricky to implement.

One possibility would be to pass the unit script _contents_ so the caller would be in control of both the template and the variables. However, it would not be straightforward to use module variables (like `@config_dir`) as the template would be expanded in the caller context.

Another possibility would be to pass the unit script _template path_ so in this case the template would be expanded in the module context. The drawback here is that it would be hard to access variables defined outside of the module.

**Comment by LionelCons** [comment]
The pull request adds an option to fix this issue.

@juniorsysadmin If you want to add support for arbitrary templates, feel free to raise a specific issue for this.
