### ISSUE TITLE
Config files should not be world readable

### ISSUE THREAD

**Issue by langesven** [voxpupuli/puppet-kafka#249]
The issues #146 and #165 already went in the right direction with making permissions more restrictive.
The default is still that config files are owned by root:root with permissions of 0644 so that the non-privileged kafka user can read the configs.
Given that keystore credentials are also specified in `server.properties` the 0644 permissions are rather broad, as anyone with access to the machine can then read the keystore credentials.
As such I'd propose being able to configure the permissions of the config files and changing the group to the configurable group parameter.
Then it's possible to have 0640 permissions with the kafka group being able to read any configs while being unable to modify anything and no other unprivileged users being able to access configs.

**Comment by bastelfreak** [comment]
Hi @langesven, thanks for bringing this up. Are you able to provide a PR with the needed adjustments?
