### ISSUE TITLE
Puppet-archive 3.0.0 support

### ISSUE THREAD

**Issue by ov7a** [voxpupuli/puppet-kafka#256]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.1
- Distribution: Debian 8
- Module version: 5.1.0

## How to reproduce (e.g Puppet code you use)
```
puppet module install puppet-archive --version 3.0.0
puppet module install puppet-kafka --version 5.1.0
```
## What are you seeing
```
Notice: Preparing to install into /etc/puppetlabs/code/environments/production/modules ...
Notice: Downloading from https://forgeapi.puppet.com ...
Error: Could not install module 'puppet-kafka' (???)
  No version of 'puppet-kafka' can satisfy all dependencies
    Use `puppet module install --ignore-dependencies` to install only this module
```
## What behaviour did you expect instead

Successful install.

## Any additional information you'd like to impart
`puppet-archive` 3.0.0 as released in May, but is not supported. As far as I can see, there are no breaking changes that may affect `puppet-kafka` module.

**Comment by bastelfreak** [comment]
Hi @ov7a, this will be fixed in https://github.com/voxpupuli/puppet-kafka/pull/275
