### ISSUE TITLE
Root owns config directory (but not files in it), ignoring $user

### ISSUE THREAD

**Issue by gla1** [voxpupuli/puppet-kafka#273]
This is driving my users nuts. Any chance the various files can be forced to respect the user setting?

**Comment by gla1** [comment]
After checking, literally the only thing root owns is the config directory. Not sure why.

**Comment by gla1** [comment]
[root@puppet manifests]# grep -R root
broker/config.pp:    owner   => 'root',
consumer/config.pp:    owner   => 'root',
producer/config.pp:    owner   => 'root',
init.pp:    owner  => 'root',
init.pp:    group  => 'root',

I lied more, it looks like there are five places with hardcoded root. Any reason? It definitely works fine without anything owned by root, so I'd love to not get yelled at by users or do hacky stuff to fix it.

**Comment by dhoppe** [comment]
To be honest, I can not answer that question. It does not make sense, since the user/group are being managed by this module. 

I will look into this issue and create an pull request, if necessary.
