### ISSUE TITLE
[Topic] Parameter --zookeeper

### ISSUE THREAD

**Issue by dhoppe** [voxpupuli/puppet-kafka#302]
> The bin/kafka-topics.sh command line tool is now able to connect directly to brokers with --bootstrap-server instead of zookeeper. The old --zookeeper option is still available for now. Please read [KIP-377](https://cwiki.apache.org/confluence/display/KAFKA/KIP-377%3A+TopicCommand+to+use+AdminClient) for more information.

**Comment by der-eismann** [comment]
Unfortunately the `--zookeeper` option is gone in kafka 3.1.0, so it is not possible to create topics.
