### ISSUE TITLE
Incorrect tag style in init.erb template causes minor bug in generated file

### ISSUE THREAD

**Issue by pmbuko** [voxpupuli/puppet-kafka#306]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: all
- Ruby: n/a
- Distribution: debian variants that still use /etc/init.d scripts (pre systemd)
- Module version: all

## How to reproduce (e.g Puppet code you use)
1. Apply `kafka::[broker,mirror,producer,consumer]` to a node
2. Inspect the INIT INFO section of the `/etc/init.d/kafka[-foo]` script
3. See the `Provides` line is missing a service name and the stripped newline causes `Required-Start` line to move up to the end of the same line

## What are you seeing
When applying the kafka service to a node -- whether it's broker, mirror, producer, or consumer -- the provides line at the top of the generated init script looks like
```
### BEGIN INIT INFO
# Provides:          # Required-Start:
```
## What behaviour did you expect instead
It should look like this
```
### BEGIN INIT INFO
# Provides:          kafka[-foo]
# Required-Start:
```
## Output log
n/a

## Any additional information you'd like to impart
Unless you have defined any `$service_requires`, the resulting init script works fine , but causes benign `insserv` errors: 
```
insserv: Script kafka is broken: incomplete LSB comment.
insserv: missing `Required-Start:' entry: please add even if empty.
insserv: script K01kafka provides facility # with comment sign, skipped!
```
If you've defined $service_requires, then they will be ignored since that line is combined with the Provides line above it.

**Comment by dhoppe** [comment]
This issue has been solved by #307.
