### ISSUE TITLE
stop trying to make fetch happen

### ISSUE THREAD

**Issue by igalic** [voxpupuli/puppet-kafka#31]
![stop trying to make fetch happen. it's not going to happen!](http://images.huffingtonpost.com/2014-06-25-fetchhappen.gif)

@voxpupuli has [puppet-archive](https://github.com/voxpupuli/puppet-archive/) which abstracts away this ad-hoc implementation of fetch, I mean wget. we should use that instead.

i realize that this is a breaking change, but perhaps it is for the better.

**Comment by dhoppe** [comment]
I think we should discuss, when [puppet-archive](https://github.com/voxpupuli/puppet-archive/) or [puppet-staging](https://github.com/voxpupuli/puppet-staging/) should be used. In my opinion puppet-staging has greater acceptance.

**Comment by jyaworski** [comment]
@dhoppe I vote for puppet-archive. It may just be that I'm more familiar with the codebase, but I feel it is more widely used than staging.

**Comment by igalic** [comment]
same.

i think we should add the features from staging that archive is missing

**Comment by dhoppe** [comment]
I tried to implement this feature, but as far aus I know archive does not support stripping of directories.
