### ISSUE TITLE
stdlib 9 support

### ISSUE THREAD

**Issue by Fabian1976** [voxpupuli/puppet-kafka#358]
Could you please support stdlib 9 (or just add < 10.0.0 as upper boundry).

**Comment by TheMeier** [comment]
Was already fixed in https://github.com/voxpupuli/puppet-kafka/commit/01bf608e5c03a329a8a5b2398c5d337605037d6e
No release was made since then...

**Comment by Fabian1976** [comment]
Tnx. Will close this then. Hope they release it soon.
