### ISSUE TITLE
kafka::mirror is critically broken

### ISSUE THREAD

**Issue by dbeckham** [voxpupuli/puppet-kafka#39]
The `kafka::mirror` class calls `kafka::mirror::config` which has a `$consumer_config` parameter that defaults to the `$kafka::params::consumer_config_defaults` variable located in `kafak::params`. This variable is a single level deep hash that contains Kafka application specific configuration properties. 

But, in `kafka::mirror::config` on line 25 (https://github.com/voxpupuli/puppet-kafka/blob/master/manifests/mirror/config.pp#L25), that same consumer config hash is passed to the Puppet `create_resources()` command, which only accepts very specific hash of Puppet resource parameters.  See: https://docs.puppetlabs.com/puppet/latest/reference/function.html#createresources

Line 25 can't work and couldn't have ever worked in any recent Puppet version. Is the mirror code only experimental and should not be used?

**Comment by dhoppe** [comment]
@dbeckham The usage of `create_resources()` is not limited to Puppet resource parameters, as you can see at our [collectd](https://github.com/voxpupuli/puppet-collectd/blob/master/manifests/plugin/network.pp#L27-L28) module. 

I have no experience with the class `kafka::mirror`, but I am pretty sure that the `create_resource()` is being used to suppress error messages like `Duplicate resource declaration ...`.
