### ISSUE TITLE
'archive' module conflict 

### ISSUE THREAD

**Issue by DjxDeaf** [voxpupuli/puppet-kafka#61]
Hi,

We are trying to use this module (and contributed some changes on the way) but we are now facing a serious issue, which prevent us from using it as the 'archive' module being used it by you (and is a great module) but we (and many modules) are using the popular camptocamp/archive module such as kibana4, grafana, etc.

thought it was worth sharing and see hear your thoughts about it

Thanks
Eliran

**Comment by thijsterlouw** [comment]
Same issue here. I had to revert back to a previous version of init.pp

**Comment by igalic** [comment]
paging @mcanevet & @raphink

**Comment by rnelson0** [comment]
@DjxDeaf @thijsterlouw Can you elaborate on the issue(s) you are running into, so we know what specifically needs to be addressed? Thanks!

**Comment by igalic** [comment]
pretty sure we can close this one now that 
https://github.com/voxpupuli/puppet-archive/issues/165
https://github.com/voxpupuli/puppet-archive/issues/174
https://github.com/voxpupuli/puppet-archive/issues/176
are mergedd
