### ISSUE TITLE
Readme states that "config" is available within the "kafka" class

### ISSUE THREAD

**Issue by loki2302** [voxpupuli/puppet-kafka#8]
Readme says that it's possible to supply the `config` hash withing the "kafka" class, but it doesn't work. Puppet says "invalid parameter".

**Comment by BaloMueller** [comment]
Same problem here! How do I supply config parameters?

**Comment by dhoppe** [comment]
Hello Andrey, 

I think you used the wrong class. The parameter **config** is only supported by the classes **kafka::broker**, **kafka::consumer** and **kafka::producer**.

Kind regards,
Dennis

**Comment by ffrank** [comment]
True. Thanks @dhoppe.

Still, this report is valid, seeing as our docs are broken. Opened #48 to fix this. Reviews are appreciated.

**Comment by igalic** [comment]
fixed in #48
