### ISSUE TITLE
Fix regexp for URL validation (or remove URL validation at all)

### ISSUE THREAD

**Issue by volkorny** [voxpupuli/puppet-kafka#92]
### Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 3.8.5
- Ruby: ruby 1.9.3p484
- Distribution: Ubuntu 14.04
- Module version: 2.0.0

### How to reproduce (e.g Puppet code you use)
```puppet
$mirror_url          = 'http://10.109.5.2:8080/plugins/kafka-0.1/repositories/ubuntu'

class { 'kafka':
  version       => $kafka_version,
  scala_version => '2.11',
  mirror_url    => $mirror_url,
}
```
### Output log

http://10.109.5.2:8080/plugins/kafka-0.1/repositories/ubuntu is not a valid url at /etc/fuel/plugins/kafka-0.1/puppet/modules/kafka/manifests/init.pp:49

**Comment by igalic** [comment]
fixed in #93.
