### ISSUE TITLE
Incompatibility beetween $install_dir and $version params

### ISSUE THREAD

**Issue by RNiveau** [voxpupuli/puppet-kafka#98]
### Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 3.7
- Ruby: 2.0.0
- Distribution: CentOs7
- Module version: 2.0.0

### How to reproduce (e.g Puppet code you use)

```
  class { '::kafka' :
    install_java => false,
    version      => '0.10.0.1',
    install_dir  => '/mydir/kafka'
  }
```
### What are you seeing

Install directory is /opt/kafka-2.11-0.10.0.1

### What behaviour did you expect instead

Install directory should be /mydir/kafka

### Any additional information you'd like to impart

I think the bug comes from this piece of code (from init.pp):

```
if $version != $kafka::params::version {
    $install_directory = "/opt/kafka-${scala_version}-${version}"
  } elsif $scala_version != $kafka::params::scala_version {
    $install_directory = "/opt/kafka-${scala_version}-${version}"
  } else {
    $install_directory = $install_dir
  }
```

**Comment by igalic** [comment]
i believe this to be fixed with #99
